# save location for model weights, experiment results, etc.
x-shared-settings: &shared-settings
  build:
    context: .
    dockerfile: Dockerfile
    args:
      UID: "${HOST_UID}"
      GID: "${HOST_GID}"
      USERNAME: "${USERNAME}"
  volumes:
    - ./outputs:/app/outputs

services:
  train-lstm:
    <<: *shared-settings
    container_name: train-lstm
    command: ["train", "--config", "configs/models/lstm.yaml"] 
    environment:
      - MODEL_TYPE=LSTM

  train-ntm:
    <<: *shared-settings
    container_name: train-ntm
    command: ["train", "--config", "configs/models/ntm.yaml"]
    environment:
      - MODEL_TYPE=NTM

  experiments:
    <<: *shared-settings
    container_name: experiments
    command: ["experiment", "--config", "configs/experiment.yaml"]
    environment:
      - EXPERIMENT_LOG_PATH=/app/outputs
